config:
  nacos:
    host: ${NACOS_HOST:127.0.0.1}:18848
    
server:
  forward-headers-strategy: framework

spring:
  cloud:
    nacos:
      username: nacos
      password: nacos
      discovery:
        server-addr: ${config.nacos.host}
        namespace: dev
      config:
        file-extension: yaml
        server-addr: ${config.nacos.host}
        namespace: dev
        group: DEFAULT_GROUP
  config:
    import: 
      - optional:nacos:octopus-gateway-config.yaml
      - optional:nacos:octopus-gateway-rate-limit-config.yaml
  data:
    redis:
      host: ${REDIS_HOST:127.0.0.1}
      port: 6379
      database: 0

cookie-domain: .aiolos.com
