config:
  nacos:
    host: ${NACOS_HOST:127.0.0.1}:8848
    
spring:
  cloud:
    nacos:
      username: nacos
      password: nacos
      discovery:
        server-addr: ${config.nacos.host}
        namespace: public
      config:
        file-extension: yaml
        server-addr: ${config.nacos.host}
        namespace: public
        group: DEFAULT_GROUP
  config:
    import: 
      - optional:nacos:octopus-gateway-config.yaml
      - optional:nacos:octopus-gateway-rate-limit-config.yaml
        
cookie-domain: .volleyshot.com