#spring:
#  cloud:
#    gateway:
#      globalcors:
#        cors-configurations:
#          '[/**]':
#            allow-credentials: true
#            allowed-origin-patterns:
#              - "http://127.0.0.1:*"
#              - "http://localhost:*"
#              - "http://*.aiolos.com:*"
#              - "https://*.volleyshot.com:*"
#            allowed-methods:
#              - GET
#              - POST
#              - OPTIONS
#            allowed-headers: "*"
#            max-age: 86400  # 预检缓存 24 小时（单位：秒）
#            # 解决 OPTIONS 请求被 403 拦截
#        add-to-simple-url-handler-mapping: true
#      default-filters:
#        - DedupeResponseHeader=Vary Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_FIRST
#      discovery:
#        locator:
#          enabled: true # 服务发现自动路由，不用配置router也能根据请求路径中的服务名路由到已注册的服务，显示配置的路由优先级更高
#          lowerCaseServiceId: true
#      routes:
#        - id: auto-docs
#          uri: lb://${serviceId}
#          predicates:
#            - Path=/{serviceId}/v3/api-docs
#          filters:
#            - RewritePath=/{serviceId}/v3/api-docs, /v3/api-docs
#
#        # 代理 Swagger 配置请求到网关自身
#        - id: swagger-config
#          uri: http://localhost:${server.port}  # 指向网关自己
#          predicates:
#            - Path=/v3/api-docs/swagger-config
#
#        - id: live-api
#          uri: lb://live-api
#          predicates:
#            - Path=/live-api/**
#          filters:
#            - StripPrefix=1
#        - id: badger-user-provider
#          uri: lb://badger-user-provider
#          predicates:
#            - Path=/badger-user-provider/**
#          filters:
#            - StripPrefix=1
#        - id: live-im-provider
#          uri: lb://live-im-provider
#          predicates:
#            - Path=/live-im-provider/**
#          filters:
#            - StripPrefix=1
#
#springdoc:
#  swagger-ui:
#    config-url: /v3/api-docs/swagger-config  # 指定动态配置入口
#    path: /doc.html
#  api-docs:
#    enabled: false  # 禁用网关自身文档
#
#dubbo:
#  application:
#    name: dubbo-live-gateway
#    qos-enable: false
#  registry:
#    address: nacos://${NACOS_HOST:127.0.0.1}:18848?namespace=dev&username=nacos&password=nacos
#  consumer:
#    check: false
#
#whitelist:
#  services:
#    - id: live-api
#      urls:
#        - /sms/send-sms
#        - /living-room/list
#      anonymous-urls:
#        - /living-room/anchor-config
#    - id: live-im-provider
#      anonymous-urls:
#        - /im/get-im-config
#    - id: badger-user-provider
#      urls:
#        - /user/login
#
#rate-limit:
#  services:
#    - id: live-im-provider
#      default-config:
#        max-requests: 20
#        time-window: 10
#        ban-time: 60
#      interfaces:
#        - path: /im/get-im-config
#          max-requests: 2
#          time-window: 10
#          ban-time: 60